// Ls3Icons.idl : IDL source for Ls3Icons
//

// This file will be processed by the MIDL tool to
// produce the type library (Ls3Icons.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(EFD58E87-69A5-4340-880C-5FD1475CE09D),
	pointer_default(unique)
]
interface ILs3IconShlExt : IUnknown{
};
[
	uuid(F52D7AB4-B85B-40C4-B088-7FD111889037),
	version(1.0),
]
library Ls3IconsLib
{
	importlib("stdole2.tlb");
	[
		uuid(9B289D33-F22D-459E-9D97-CD9FBB326D35)		
	]
	coclass Ls3IconShlExt
	{
		[default] interface ILs3IconShlExt;
	};
};

